id: boundary
type: polygon
queries:
  - minZoom: 0
    maxZoom: 14
    sql: |
      SELECT id, tags, geom 
      FROM osm_simplified_ways_z${zoom} 
      WHERE tags ? 'boundary'
  - minZoom: 0
    maxZoom: 14
    sql: |
      SELECT id, tags, geom 
      FROM osm_simplified_relations_z${zoom} 
      WHERE tags ? 'boundary'
  - minZoom: 14
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways 
      WHERE tags ? 'boundary'
  - minZoom: 14
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_relations 
      WHERE tags ? 'boundary'