id: boundary
type: polygon
queries:
  - minZoom: 0
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom} 
      WHERE tags ? 'boundary'
  - minZoom: 0
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_relations_z${zoom} 
      WHERE tags ? 'boundary'