id: OpenStreetMapVecto
server:
  host: localhost
  port: 9000
center:
  lon: 6.6323
  lat: 46.5197
  zoom: 12
bounds:
  minLon: -180
  minLat: -85.05113
  maxLon: 180
  maxLat: 85.05113
  minZoom: 0
  maxZoom: 20
components:
  - components/points.yaml
  - components/aerialway.yaml
  - components/railway.yaml
  - components/highway.yaml
  - components/building.yaml
  - components/waterway.yaml
  - components/water.yaml
  - components/leisure.yaml
  - components/landuse.yaml
  - components/amenity.yaml
  - components/background.yaml
layers:
  - layers/aerialway.yaml
  - layers/amenity.yaml
  - layers/building.yaml
  - layers/highway.yaml
  - layers/landuse.yaml
  - layers/leisure.yaml
  - layers/points.yaml
  - layers/railway.yaml
  - layers/waterway.yaml
  - layers/water.yaml
