id: OpenStreetMapVecto
server:
  host: localhost
  port: 9000
center:
  lon: 6.6323
  lat: 46.5197
  zoom: 12
bounds:
  minLon: -180
  minLat: -85.05113
  maxLon: 180
  maxLat: 85.05113
  minZoom: 12
  maxZoom: 18
layers:
  - config/aerialway/layer.yaml
  - config/amenity/layer.yaml
  - config/building/layer.yaml
  - config/highway/layer.yaml
  - config/landuse/layer.yaml
  - config/leisure/layer.yaml
  - config/points/layer.yaml
  - config/railway/layer.yaml
  - config/waterway/layer.yaml
  - config/water/layer.yaml
stylesheets:
  - config/points/stylesheet.yaml
  - config/aerialway/stylesheet.yaml
  - config/railway/stylesheet.yaml
  - config/highway/stylesheet.yaml
  - config/building/stylesheet.yaml
  - config/waterway/stylesheet.yaml
  - config/water/stylesheet.yaml
  - config/leisure/stylesheet.yaml
  - config/landuse/stylesheet.yaml
  - config/amenity/stylesheet.yaml
  - config/background/stylesheet.yaml
