version: '3.8'

networks:
  lan_access:
    driver: bridge

services:
  baremaps:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: unless-stopped
    networks:
      - lan_access
    ports:
      - "${DB_HOST_PORT}:5432"
      - "${DB_APP_PORT}:${DB_APP_PORT}"
    working_dir: ${OSMVECTO_PATH}
    volumes:
      - ./:${OSMVECTO_PATH} # !!! dev only
    # Run only once at startup to populate the database (it takes some time)
    # comment this line after and uncomment the following to actually start
    # the app.
    entrypoint: "./populate-db.sh"
    #entrypoint: "${OSMVECTO_PATH}/entrypoint.sh"
