id: building
styles:
  - id: building
    layer: building
    type: fill
    layout:
      visibility: visible
    paint:
      fill-color: rgb(216, 208, 201)
      fill-antialias: true
      fill-outline-color: rgb(199, 185, 174)

  - id: building_number
    layer: building
    type: symbol
    layout:
      text-allow-overlap: false
      text-anchor: center
      text-field: "{addr:housenumber}"
      text-font: ["Noto Sans Regular"]
      text-offset: [0,0]
      text-size: 
        stops: [
          [15,0],
          [16, 11],
          [20, 11]
        ]
      visibility: visible
    paint:
      text-color: rgb(96,96,96)
      text-halo-color: rgba(255,255,255,0.8)
      text-halo-width: 1.2  
