id: building
styles:
  - id: building
    layer: building
    type: fill
    layout:
      visibility: visible
    paint:
      fill-color: rgb(216, 208, 201)
      fill-antialias: true
      fill-outline-color: rgb(199, 185, 174)