id: points
type: point
queries:
  - minZoom: 14
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_nodes
      WHERE geometrytype(geom) LIKE '%POINT%'
        AND tags ? 'natural'
  - minZoom: 7
    maxZoom: 15
    sql: |
      SELECT id, tags, geom 
      FROM osm_nodes
      WHERE geometrytype(geom) LIKE '%POINT%'
        AND tags -> 'place' IN (
          'city','town')
  - minZoom: 11
    maxZoom: 17
    sql: |
      SELECT id, tags, geom 
      FROM osm_nodes
      WHERE geometrytype(geom) LIKE '%POINT%'
        AND tags -> 'place' IN (
          'village','borough')     
  - minZoom: 13
    maxZoom: 17
    sql: |
      SELECT id, tags, geom 
      FROM osm_nodes
      WHERE geometrytype(geom) LIKE '%POINT%'
        AND tags -> 'place' IN (
          'allotments','city-block','farm','hamlet','isolated_dwelling','neighbourhood','suburb','quarter','plot')