id: points
styles:
  - id: building_number_node
    layer: points
    type: symbol
    layout:
      text-allow-overlap: false
      text-anchor: center
      text-field: "{addr:housenumber}"
      text-font: ["Noto Sans Regular"]
      text-offset: [0,0]
      text-size: 
        stops: [
          [15,0],
          [16, 11],
          [20, 11]
        ]
      visibility: visible
    paint:
      text-color: rgb(96,96,96)
      text-halo-color: rgba(255,255,255,0.8)
      text-halo-width: 1.2   
  - id: natural_trunk
    layer: points
    type: circle
    layout:
      visibility: visible
    filter: [
      all,
      [==, natural, tree]
    ]
    paint:
      circle-color: rgb(129, 94, 39)
      circle-opacity: 1
      circle-radius:
        stops: [
          [14, 0.25],
          [15, 0.5],
          [16, 1],
          [17, 2],
          [18, 4],
        ]
  - id: natural_tree
    layer: points
    type: circle
    layout:
      visibility: visible
    filter: [
      all,
      [==, natural, tree]
    ]
    paint:
      circle-color: rgb(113, 205, 111)
      circle-opacity: 1
      circle-radius:
        stops: [
          [14, 0.75],
          [15, 1.5],
          [16, 3],
          [17, 6],
          [18, 12],
        ]
  - id: power_tower
    layer: points
    type: circle
    layout:
      visibility: visible
    filter: [
      any,
      [==, power, tower], 
      [==, power, pole], 
      [==, power, portal], 
      [==, power, catenary_mast],
    ]
    paint:
      circle-color: rgb(171, 171, 171)
      circle-opacity: 1
      circle-radius:
        stops: [
          [13, 1],
          [14, 2],
          [15, 3],
          [16, 4],
          [17, 5],
          [18, 6],
        ]
  