id: points
styles:
  - id: place_label_city
    layer: points
    type: symbol
    layout:
      text-allow-overlap: true
      text-anchor: bottom
      text-field: "{name}"
      text-font: ["Noto Sans Regular"]
      text-max-width: 8
      text-offset: [0,0]
      text-size: 
        stops: [
          [7, 15],
          [15, 19]
        ]
      visibility: visible
    filter: [
      all,
      [==, place,'city']
    ]
    paint:
      text-color: rgb(0,0,0)
      text-halo-color: rgba(255,255,255,0.8)
      text-halo-width: 1.2
  - id: place_label_town
    layer: points
    type: symbol
    layout:
      text-anchor: bottom
      text-field: "{name}"
      text-font: ["Noto Sans Regular"]
      text-max-width: 8
      text-offset: [0,0]
      text-size: 
        stops: [
          [7, 11],
          [15, 19]
        ]
      visibility: visible
    filter: [
      all,
      [==, place,'town']
    ]
    paint:
      text-color: rgb(0,0,0)
      text-halo-color: rgba(255,255,255,0.8)
      text-halo-width: 1.2
  - id: place_label_village
    layer: points
    type: symbol
    layout:
      text-anchor: bottom
      text-field: "{name}"
      text-font: ["Noto Sans Regular"]
      text-max-width: 8
      text-offset: [0,0]
      text-size: 
        stops: [
          [11, 13],
          [17, 19]
        ]
      visibility: visible
    filter: [
      any,
      [==, place,'village'],
      [==, place,'borough']
    ]
    paint:
      text-color: rgb(96,96,96)
      text-halo-color: rgba(255,255,255,0.8)
      text-halo-width: 1.2
  - id: place_label_quarter
    layer: points
    type: symbol
    layout:
      text-anchor: bottom
      text-field: "{name}"
      text-font: ["Noto Sans Regular"]
      text-max-width: 8
      text-offset: [0,0]
      text-size: 
        stops: [
          [13, 12],
          [17, 16]
        ]
      visibility: visible
    filter: [
      any,
      [==, place,'allotments'],
      [==, place,'city-block'],
      [==, place,'farm'],
      [==, place,'hamlet'],
      [==, place,'isolated_dwelling'],
      [==, place,'neighbourhood'],
      [==, place,'suburb'],
      [==, place,'quarter'],
      [==, place,'plot']
    ]
    paint:
      text-color: rgb(96,96,96)
      text-halo-color: rgba(255,255,255,0.8)
      text-halo-width: 1.2

  - id: natural_trunk
    layer: points
    type: circle
    layout:
      visibility: visible
    filter: [
      all,
      [==, natural, tree]
    ]
    paint:
      circle-color: rgb(129, 94, 39)
      circle-opacity: 1
      circle-pitch-alignment: map
      circle-radius:
        stops: [
          [14, 0.25],
          [15, 0.5],
          [16, 1],
          [17, 2],
          [18, 4],
        ]
  - id: natural_tree
    layer: points
    type: circle
    layout:
      visibility: visible
    filter: [
      all,
      [==, natural, tree]
    ]
    paint:
      circle-color: rgb(113, 205, 111)
      circle-opacity: 1
      circle-pitch-alignment: map
      circle-radius:
        stops: [
          [14, 0.75],
          [15, 1.5],
          [16, 3],
          [17, 6],
          [18, 12],
        ]
  - id: power_tower
    layer: points
    type: circle
    layout:
      visibility: visible
    filter: [
      any,
      [==, power, tower], 
      [==, power, pole], 
      [==, power, portal], 
      [==, power, catenary_mast],
    ]
    paint:
      circle-color: rgb(171, 171, 171)
      circle-opacity: 1
      circle-radius:
        stops: [
          [13, 1],
          [14, 2],
          [15, 3],
          [16, 4],
          [17, 5],
          [18, 6],
        ]
  