id: amenity
type: polygon
queries:
  - minZoom: 13
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways
      WHERE geometrytype(geom) LIKE '%POLYGON%'
        AND tags ? 'amenity'