id: amenity
styles:
  - id: amenity_parking
    layer: amenity
    type: fill
    layout:
      visibility: visible
    filter: [
      any,
      [==, amenity, parking],
      [==, amenity, motorcycle_parking],
    ]
    paint:
      fill-color: rgb(238, 238, 238)
      fill-antialias: true
      fill-outline-color: rgb(222, 214, 214)
  - id: amenity_education
    layer: amenity
    type: fill
    layout:
      visibility: visible
    filter: [
      any,
      [==, amenity, kindergarten],
      [==, amenity, school],
      [==, amenity, college],
      [==, amenity, university],
    ]
    paint:
      fill-color: rgb(255, 255, 228)
      fill-antialias: true