id: 'openstreetmap'
center:
  lon: 6.6323
  lat: 46.5197
  zoom: 0
bounds:
  minLon: -180
  maxLon: 180
  minLat: -90
  maxLat: 90
  minZoom: 0
  maxZoom: 18
layers:
  - id: 'boundary'
    type: 'geometry'
    queries:
      - minZoom: 0
        maxZoom: 2
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_110m_admin_0_boundary_lines_land AS t
      - minZoom: 2
        maxZoom: 4
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_50m_admin_0_boundary_lines_land AS t
      - minZoom: 4
        maxZoom: 6
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_10m_admin_0_boundary_lines_land AS t
  - id: 'water'
    type: 'geometry'
    queries:
      - minZoom: 0
        maxZoom: 2
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_110m_ocean AS t
      - minZoom: 0
        maxZoom: 2
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_110m_lakes AS t
      - minZoom: 2
        maxZoom: 4
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_50m_ocean AS t
      - minZoom: 2
        maxZoom: 4
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_50m_lakes AS t
      - minZoom: 4
        maxZoom: 6
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_10m_ocean AS t
      - minZoom: 4
        maxZoom: 6
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_10m_lakes AS t
  - id: 'landuse'
    type: 'geometry'
    queries:
      - minZoom: 2
        maxZoom: 4
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_50m_urban_areas AS t
      - minZoom: 4
        maxZoom: 6
        sql: SELECT ogc_fid as id, hstore(t.*) as tags, geometry FROM ne_10m_urban_areas AS t