id: natural
type: polygon
queries:
  - minZoom: 0
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom}
      WHERE geometrytype(geom) LIKE '%POLYGON%' 
        AND tags ? 'natural'
  - minZoom: 0
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_relations_z${zoom}
      WHERE geometrytype(geom) LIKE '%POLYGON%'
        AND tags ? 'natural'
  - minZoom: 14
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom}
      WHERE geometrytype(geom) LIKE '%LINE%'
        AND tags ? 'natural'
