id: natural
styles:
  - id: natural_natural
    layer: natural
    type: fill
    layout:
      visibility: visible
    paint:
      fill-color: [
        'match',
        ['get', 'natural'],
        'glacier',
        'rgb(221, 236, 236)',
        'wood',
        'rgb(157, 202, 138)',
        'scrub',
        'rgb(201, 216, 173)',
        'heath',
        'rgb(214, 217, 159)',
        'grassland',
        'rgb(207, 236, 177)',
        'bare_rock',
        'rgb(217, 212, 206)',
        'scree',
        'rgb(232, 223, 216)',
        'shingle',
        'rgb(232, 223, 216)',
        'sand',
        'rgb(240, 229, 196)',
        'rgb(242, 239, 233)' #same as background color

      ]
      fill-antialias: true
