id: waterway
type: polygon
queries:
  - minZoom: 0
    maxZoom: 10
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom}
      WHERE geometrytype(geom) LIKE '%LINESTRING%'
        AND tags -> 'waterway' IN ('river')
  - minZoom: 10
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom}
      WHERE geometrytype(geom) LIKE '%LINESTRING%'
        AND tags ? 'waterway'
