id: waterway
styles:
  - id: waterway
    layer: waterway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 12]
        ]
      line-color: rgb(170, 211, 223)