id: waterway
styles:
  - id: waterway
    layer: waterway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    paint:
      line-width: 6
      line-color: rgb(170, 211, 223)