id: 'water'
styles:
  - id: water
    layer: water
    type: fill
    layout:
      visibility: visible
    paint:
      fill-color: rgb(170, 211, 223)
      fill-antialias: true
      fill-outline-color: rgb(170, 211, 223)